timeout: 1800s
steps:
- # Check that we can install important libraries without error
  name: gcr.io/gcp-runtimes/structure_test:latest
  args: [
    '-i', '${_DOCKER_NAMESPACE}/python:${_TAG}',
    '--config', '/workspace/tests/python2-libraries/python2-libraries.yaml',
    '--config', '/workspace/tests/python3-libraries/python3-libraries.yaml',
    '-v'
    ]
  env: [
    # Avoid warning about unused substitutions
    'UNUSED1=${_BUILDER_DOCKER_NAMESPACE}',
    ]
images: [
]
