timeout: 7200s
steps:
- # Compile Python interpreters from source
  name: gcr.io/cloud-builders/docker:latest
  args: ['build', '--tag=${_DOCKER_NAMESPACE}/python/interpreter-builder:${_TAG}',
         '--no-cache', '/workspace/python-interpreter-builder/']
- # Copy interpreters back to workspace
  name: ${_DOCKER_NAMESPACE}/python/interpreter-builder:${_TAG}
  args: ['cp', '/interpreters.tar.gz', '/workspace/runtime-image/interpreters.tar.gz']
- # Build base runtime image
  name: gcr.io/cloud-builders/docker:latest
  args: ['build', '--tag=${_DOCKER_NAMESPACE}/python:${_TAG}',
         '--no-cache', '/workspace/runtime-image/']
- # Build runtime builder image
  name: gcr.io/cloud-builders/docker:latest
  args: ['build', '--tag=${_BUILDER_DOCKER_NAMESPACE}/python/gen-dockerfile:${_TAG}',
         '--no-cache', '/workspace/builder/gen-dockerfile/']
images: [
  '${_DOCKER_NAMESPACE}/python/interpreter-builder:${_TAG}',
  '${_DOCKER_NAMESPACE}/python:${_TAG}',
  '${_BUILDER_DOCKER_NAMESPACE}/python/gen-dockerfile:${_TAG}',
]
