timeout: 1800s
steps:
- # Check that we can install important libraries without error
  name: gcr.io/gcp-runtimes/structure_test:latest
  args: [
    '-i', '${_DOCKER_NAMESPACE}/python:${_TAG}',
    '--config', '/workspace/tests/python2-libraries/python2-libraries.yaml',
    '--config', '/workspace/tests/python3-libraries/python3-libraries.yaml',
    '-v'
    ]
  env: [
    # Avoid warning about unused substitutions
    'UNUSED1=${_BUILDER_DOCKER_NAMESPACE}',
    ]
- # Run compatibility tests
  name: gcr.io/cloud-builders/docker:latest
  args: ['build', '--tag=${_DOCKER_NAMESPACE}/python/tests/eventlet:${_TAG}',
         '--no-cache', '/workspace/tests/eventlet/']
images: [
]
